export const GET_ALL_RESTAURANT = "GET_ALL_RESTAURANT";
export const SELECT_RESTAURANT = "SELECT RESTAURANT";
export const REMOVE_RESTAURANT = "REMOVE_RESTAURANT";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ITEMS_FOR_CATEGORY = "GET_ITEMS_FOR_CATEGORY";
export const GET_FOOD_ITEM_TYPES = "GET_FOOD_ITEM_TYPES";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
