export const GET_ALL_RESTAURANT = "GET_ALL_RESTAURANT";
export const SELECT_RESTAURANT = "SELECT RESTAURANT";
export const REMOVE_RESTAURANT = "REMOVE_RESTAURANT";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
